# Generated by Django 4.2.9 on 2024-01-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxipost',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
