# Generated by Django 4.2.9 on 2024-01-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0002_taxipost_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxipost',
            name='comments',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
