# Generated by Django 4.2.9 on 2024-01-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0003_alter_taxipost_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxipost',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='taxipost',
            name='date',
            field=models.DateField(),
        ),
    ]
